# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'hospital_demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hospital_demo
  pod 'Firebase/Core', '~> 5.20.1'

  target 'hospital_demoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'hospital_demo-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for hospital_demo-tvOS

  target 'hospital_demo-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
